# Base Configuration for Medical Multimodal Model

experiment:
  name: "Base_Model"
  descriptsion: "encoder:resnet50, decoder:gpt2"
  seed: 42


# Misc
seed: 42


# Paths
data:
  raw_dir: "data/raw/ROCO/all_data"
  processed_dir: "data/processed"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Model Architecture
model:
  vision_encoder:
    name: "resnet50"  # Options: resnet50, resnet101, vit_base, vit_large
    pretrained: true
    freeze_backbone: false
    feature_dim: 2048
  
  language_decoder:
    name: "gpt2"  # Options: gpt2, gpt2-medium, bart-base, t5-small
    pretrained: true
    vocab_size: 50257
    max_length: 256
    
  fusion:
    attention_heads: 8
    hidden_dim: 512
    dropout: 0.1

# Training
training:
  batch_size: 16
  num_epochs: 10
  learning_rate: 1e-4
  weight_decay: 1e-5
  warmup_steps: 1000
  gradient_clip: 1.0
  
  optimizer:
    name: "adamw"  # Options: adam, adamw, sgd
    
  scheduler:
    name: "cosine"  # Options: cosine, linear, step
    
  early_stopping:
    patience: 5
    min_delta: 0.001

# Data Augmentation
augmentation:
  image:
    resize: [224, 224]
    normalize: true
    random_flip: 0.5
    random_rotation: 10
    brightness: 0.1
    contrast: 0.1
    
  text:
    max_length: 256
    truncation: true
    padding: "max_length"

# Evaluation
evaluation:
  metrics: ["bleu", "rouge", "meteor", "cider"]
  beam_size: 3
  num_beams: 5
  temperature: 0.8

# Hardware
hardware:
  device: "cuda"  # Options: cuda, cpu
  num_workers: 0
  pin_memory: true
  mixed_precision: true

# Logging
logging:
  log_dir: "logs"
  save_dir: "models/checkpoints"
  save_freq: 1  # Save every N epochs
  use_wandb: true
  project_name: "medical-multimodal"


# Validation
validation:
  batch_size: 32
  eval_every: 1
  num_samples: 5

# Checkpoints
checkpoint:
  save_best_only: true
  monitor: "val_loss"
  mode: "min"
  save_last: true
  resume_from: null

# Generation (Inference)
generation:
  max_new_tokens: 256
  min_length: 10
  do_sample: true
  top_k: 50
  top_p: 0.95
  temperature: 0.8
  repetition_penalty: 1.2
  num_return_sequences: 1

# Debug Mode (optional)
debug:
  enabled: false
  num_train_samples: 100
  num_val_samples: 20
  fast_dev_run: false  # 1 epoch만 빠르게 실행